services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/app
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    links:
      - backend
    volumes:
      - ./client:/app
